version: '3.8'
services:
  db:
    container_name: db-ignite
    image: postgres:14.4
    restart: always
    ports: 
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}